"""add system role to message_role enum

Revision ID: d01c1c34bc05
Revises: 5b2924d08cbf
Create Date: 2026-05-06 01:50:13.588537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'd01c1c34bc05'
down_revision: Union[str, Sequence[str], None] = '5b2924d08cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['user', 'assistant', 'system'],
        affected_columns=[TableReference(table_schema='public', table_name='chat_messages', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['user', 'assistant'],
        affected_columns=[TableReference(table_schema='public', table_name='chat_messages', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###